package com.arsisec.model.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _PPersona was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PPersona extends CayenneDataObject {

    public static final String NOMBRE_PROPERTY = "nombre";

    public static final String ID_PK_COLUMN = "id";

    public void setNombre(String nombre) {
        writeProperty(NOMBRE_PROPERTY, nombre);
    }
    public String getNombre() {
        return (String)readProperty(NOMBRE_PROPERTY);
    }

}
